name: Deployment

on:
  workflow_dispatch:
    inputs:
      bump_level:
        description: 'Release level for the stable version (patch, minor, major)'
        required: false
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Bump version and create tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: main
        default_bump: ${{ github.event.inputs.bump_level }}
        tag_prefix: v

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run preprocessing script
      run: |
        python sentiment_analysis_preprocessing/preprocess.py

    - name: Rename output files with version
      run: |
        mv output/preprocessor.joblib output/preprocessor-v${{ steps.tag_version.outputs.new_tag }}.joblib
        mv output/preprocessed_data.joblib output/preprocessed_data-v${{ steps.tag_version.outputs.new_tag }}.joblib

    - name: Upload generated files as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sentiment-pipeline-artifacts-${{ steps.tag_version.outputs.new_tag }}
        path: |
          output/preprocessor-v${{ steps.tag_version.outputs.new_tag }}.joblib
          output/preprocessed_data-v${{ steps.tag_version.outputs.new_tag }}.joblib

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        files: |
          output/preprocessor-v${{ steps.tag_version.outputs.new_tag }}.joblib
          output/preprocessed_data-v${{ steps.tag_version.outputs.new_tag }}.joblib
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Bump patch and add pre tag
      id: bump_patch
      if: github.ref == 'refs/heads/main'
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: '_NONE_'
        pre_release_branches: main
        default_prerelease_bump: prerelease
        append_to_pre_release_tag: pre
        tag_prefix: v
        default_bump: patch
