name: Integration

on:
  pull_request:
    branches: [main]
    paths-ignore: [".github/**", "README.md"] 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Download NLTK stopwords
        run: |
          python -c "import nltk; nltk.download('stopwords')"

      - name: Show installed packages
        run: pip list

      - name: Run smoke test
        run: |
          echo "Testing sample input"
          python -c "from sentiment_analysis_preprocessing.preprocess import preprocess; preprocess(['I am not happy with the service.'])"
