# Workflow for integration tests
name: Integration

# This workflow runs integration tests on pull requests to the main branch
on:
  pull_request:
    branches: [main]
    paths-ignore: [".github/**", "README.md"] 

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      # Checkout the repository
      - name: Checkout source
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      # Install additional dependencies for testing
      - name: Download NLTK stopwords
        run: |
          python -c "import nltk; nltk.download('stopwords')"

      # Show all installed packages
      - name: Show installed packages
        run: pip list

      # Try running the preprocessing script with a sample input
      - name: Run smoke test
        run: |
          echo "Testing sample input"
          python -c "from sentiment_analysis_preprocessing.preprocess import preprocess; preprocess(['I am not happy with the service.'])"
