name: Release Library

on:
  push:
    tags:
      - 'v*'  # Trigger only when a Git tag is pushed.

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools twine

      - name: Build distribution packages
        run: |
          python setup.py sdist bdist_wheel
        # 确保打包输出在 dist/ 目录下出现 .tar.gz 和 .whl 文件

      - name: Publish to GitHub Python Packages
        run: |
          twine upload --repository-url \
            https://api.github.com/orgs/${{ github.repository_owner }}/packages/pypi/upload \
            dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
